spring:
  mvc:
    apiversion:
      use:
#        header: X-API-VERSION
#        pathSegment: 1
        queryParameter: X-API-VERSION
#        mediaTypeParameter:
#          "[application/json]": "X-API-VERSION"
      supported:
        - 1.3
        - 1.6
      required: false