spring:
  mvc:
    apiversion:
      use:
#        header: X-API-VERSION
#        pathSegment: 1
#        queryParameter: X-API-VERSION
        mediaTypeParameter:
          "[application/json]": "X-API-VERSION"